# Generated by Django 5.0.7 on 2024-08-02 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='category',
            field=models.IntegerField(),
        ),
    ]
